# Functions

function getMace(i: item) :: string:
    if name of {_i} contains "&7Wind Mace":
        return "wind"
    else if name of {_i} contains "&cDetonate Mace":
        return "detonate"
    else if name of {_i} contains "&5Void mace":
        return "void"

function isMace(i: item) :: boolean:
    if name of {_i} contains "&7Wind Mace" or "&cDetonate Mace" or "&5Void mace":
        return true
    else:
        return false

function giveMace(p: player, t: text):
    if {_t} is "wind":
        give 1 of {-wind.mace} to {_p}
    else if {_t} is "detonate":
        give {-detonate.mace} to {_p} 
    else if {_t} is "void":
        give {-void.mace} to {_p}
