# Functions

function getMace(i: item) :: string:
    if name of {_i} contains "&7Wind Mace":
        return "wind"
    else if name of {_i} contains "&cDetonate Mace":
        return "detonate"
    else if name of {_i} contains "&5Void mace":
        return "void"

function isMace(i: item) :: boolean:
    if name of {_i} contains "&7Wind Mace" or "&cDetonate Mace" or "&5Void mace":
        return true
    else:
        return false
