# Functions

function getMace(i: item) :: string:
	if name of {_i} contains "&7Wind Mace":
		return "wind"
	else if name of {_i} contains "&cDetonate Mace":
		return "detonate"
	else if name of {_i} contains "&5Void mace":
		return "void"

function isMace(i: item) :: boolean:
	if name of {_i} contains "&7Wind Mace" or "&cDetonate Mace" or "&5Void mace":
		return true
	else:
		return false

function giveMace(p: player, t: text):
	if {_t} is "wind":
		give 1 of {-wind.mace} to {_p}
	else if {_t} is "detonate":
		give {-detonate.mace} to {_p} 
	else if {_t} is "void":
		give {-void.mace} to {_p}

function actionbar(p: player, t: text):
	set {_uuid} to {_p}'s uuid
	# Wind Mace
	if isMace({_p}'s {_t}) is true:
		if getMace({_p}'s {_t}) is "wind":
			set {_cd} to getMace({_p}'s {_t})
			if {-%{_cd}%cd::%{_uuid}%} > 0:
				send action bar "&b%{-%{_cd}%cd::%{_uuid}%}%" to {_p}
		# Detonate Mace
		if getMace({_p}'s {_t}) is "detonate":
			set {_cd} to getMace({_p}'s {_t})
			if {-%{_cd}%cd::%{_uuid}%} > 0:
				send action bar "&b%{-%{_cd}%cd::%{_uuid}%}%" to {_p}

function setCooldown(c: text, v: int, p: player):
	set {_uuid} to {_p}'s uuid
	if {_c} is "wind":
		set {%{_c}%cd::%{_uuid}%} to {_v}
	if {_c} is "detonate":
		set {%{_c}%cd::%{_uuid}%} to {_v}

function cooldownsystem(p: player):
	set {_uuid} to {_p}'s uuid
	# wind Cds
	if {-windcd::%{_uuid}%} is not set:
		set {-windcd::%{_uuid}%} to 30
	if {-windcd::%{_uuid}%} > 0:
		remove 1 from {-windcd::%{_uuid}%}
	if {-windcd::%{_uuid}%} < 0:
		set {-windcd::%{_uuid}%} to 0
	# Detonator
	if {-detonatecd::%{_uuid}%} is not set:
		set {-detonatecd::%{_uuid}%} to 30
	if {-windcd::%{_uuid}%} > 0:
		remove 1 from {-detonatecd::%{_uuid}%}
	if {-windcd::%{_uuid}%} < 0:
		set {-detonatecd::%{_uuid}%} to 0

function isReady(p: player, t: text) :: boolean:
	set {_uuid} to {_p}'s uuid
	if {%{_t}%cd::%{_uuid}%} is 0:
		return true
	else if {%{_t}%cd::%{_uuid}%} > 0:
		return false


# BLACK HOLE STUFF

function blackholeParticles(l: loc, p: player):
	set {_uuid} to {_p}'s uuid
	if {-blackhole::%{_uuid}%} is true:
		loop 150 times:
			draw 4 of dust using dustTransition(purple, black, 5) at {_vloc} with offset vector(0.5 0.7 0.5) with extra 0.5 with force
			draw 2 of smoke at {_vloc} with offset vector(0.1, 1, 0.2) with force extra 0.8 with force
			wait 1 tick

function blackholePull(p: player, p2: player):
	set {_vloc} to {_p2}'s location
	set {_d} to direction from {_p} to {_vloc}
	set {_uuid} to {_p}'s uuid
	set {-blackhole::%{_uuid}%} to true
	loop 80 times:
		loop all players:
			if IsTrusted({_p}, loop-player) is false:
				push loop-player {_d} with speed 0.5
				damage loop-player by 4
				blackholeParticles({_vloc})
				wait 5 ticks
	set {-blackhole::%{_uuid}%} to false